export const CharacterIds = {
  Akekuri: "akekuri",
  Alesh: "alesh",
  Antal: "antal",
  Arclight: "arclight",
  Ardelia: "ardelia",
  Avywenna: "avywenna",
  Catcher: "catcher",
  ChenQianyu: "chen-qianyu",
  DaPan: "da-pan",
  Ember: "ember",
  Endministrator: "endministrator",
  Estella: "estella",
  Fluorite: "fluorite",
  Gilberta: "gilberta",
  Laevatain: "laevatain",
  LastRite: "last-rite",
  Lifeng: "lifeng",
  Perlica: "perlica",
  Pogranichnik: "pogranichnik",
  Rossi: "rossi",
  Snowshine: "snowshine",
  Tangtang: "tangtang",
  Wulfgard: "wulfgard",
  Xaihi: "xaihi",
  Yvonne: "yvonne",
  ZhuangFangyi: "zhuang-fangyi",
} as const;
