export const GearSetIds = {
  AburreysLegacy: "aburreys-legacy",
  Aethertech: "aethertech",
  AICHeavy: "aic-heavy",
  AICLight: "aic-light",
  ArmoredMSGR: "armored-msgr",
  BasicGearPack: "basic-gear-pack",
  Bonekrusha: "bonekrusha",
  Catastrophe: "catastrophe",
  EternalXiranite: "eternal-xiranite",
  Frontiers: "frontiers",
  HotWork: "hot-work",
  LYNX: "lynx",
  MISecurity: "mi-security",
  MinerAGearPack: "miner-α-gear-pack",
  MinerBGearPack: "miner-β-gear-pack",
  MinerYGearPack: "miner-γ-gear-pack",
  MordvoltInsulation: "mordvolt-insulation",
  MordvoltResistant: "mordvolt-resistant",
  PulserLabs: "pulser-labs",
  Qingbo: "qingbo",
  RedeemerGearPack: "redeemer-gear-pack",
  RovingMSGR: "roving-msgr",
  Swordmancer: "swordmancer",
  TideSurge: "tide-surge",
  Type50Yinglung: "type-50-yinglung",
  Xiranflow: "xiranflow",
} as const;
