export const RaceIds = {
  Anasa: "anasa",
  Anaty: "anaty",
  Caprinae: "caprinae",
  Cautus: "cautus",
  Feline: "feline",
  Kuranta: "kuranta",
  Kylin: "kylin",
  Liberi: "liberi",
  Lung: "lung",
  Lupo: "lupo",
  Perro: "perro",
  Phidia: "phidia",
  Sankta: "sankta",
  Sarkaz: "sarkaz",
  Savra: "savra",
  Undisclosed: "undisclosed",
  Ursus: "ursus",
  Vouivre: "vouivre",
  Vulpo: "vulpo",
} as const;
